name: Python ci


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_COLOR: "1" # Make tools pretty.
  PLAYWRIGHT_PATCH_TIMEOUT_MILLIS: "30000"

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.8", "pypy3.9" ]
        runs-on: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    env:
      TOX_TESTENV_PASSENV: "XAUTHORITY DISPLAY"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install tox
        run: |
          python -VV
          python -m site
          python -m pip install "tox>=3,<4"

      #      - run: xvfb-run -- python -m tox -e py
      #        if: runner.os == 'Linux'

      - run: python -m tox -e py
  #        if: runner.os != 'Linux'



  mypy:
    name: Mypy on ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: python -Im pip install --upgrade wheel tox
      - run: python -Im tox run -e mypy